---

- name: Installation of InfluxDB for Ubuntu
  apt:
    name: influxdb
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Installation of InfluxDB for CentOS
  yum:
    name: influxdb
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"



# tasks file for influxdb
