---
- name: Stop firewall
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Download and unarchive nagios core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create make file
  shell: cd /tmp/nagioscore-nagios-4.4.6; sh /tmp/nagioscore-nagios-4.4.6/configure --with-httpd-conf=/etc/apache2/sites-enabled
  register: make_file

- name: Compile from source
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: all
  become: yes

- name: Create user and group
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install-groups-users
  become: yes

- name: Add www-data user to nagios group
  user:
    name: www-data
    groups: nagios
    append: yes

- name: Install binaries
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install
  become: yes

- name: Install service
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install-daemoninit
  become: yes

- name: Install command mode
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install-commandmode
  become: yes

- name: Install configuration files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install-config
  become: yes

- name: Install apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6
    target: install-webconf
  become: yes
  register: install_webconf

- name: Enable rewrite module
  apache2_module:
    state: present
    name: rewrite

- name: Enable cgi module
  apache2_module:
    state: present
    name: cgi



# tasks file for nagios_ubuntu
