---

- name: Installation of Grafana for Ubuntu server
  apt:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Installation of Grafana for CentOS server
  yum:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"




# tasks file for grafana
