---

- name: Stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Download and unarchive nagios core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create make file
  shell: cd /tmp/nagioscore-nagios-4.4.6; sh /tmp/nagioscore-nagios-4.4.6/configure
  register: make_file

- name: Compile from source
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: all
  become: yes

- name: Create user and group
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install-groups-users
  become: yes

- name: add apache to nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: Install binaries
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install
  become: yes

- name: Install services
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install-daemoninit
  become: yes
  register: daemoninit

- name: Enable httpd
  service:
    name: httpd
    enabled: yes

- name: Install command mode
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install-commandmode
  become: yes

- name: Install configuration files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install-config
  become: yes

- name: Install apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.6/
    target: install-webconf
  become: yes
  register: install_webconf

