---

- name: Create etc prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    mode: "0755"

- name: Create var lib prometheus directory
  file:
    path: /var/run/prometheus
    state: directory
    mode: "0755"

- name: Download and unarchive prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.darwin-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: prometheus_archive

- name: Copy prometheus to bin
  shell: "cp /tmp/prometheus-2.39.1.darwin-amd64/prometheus /usr/local/bin/"

- name: Copy promtool to bin
  shell: "cp /tmp/prometheus-2.39.1.darwin-amd64/promtool /usr/local/bin"

- name: Make prometheus executable
  file:
    path: /usr/local/bin/prometheus
    mode: "0755"

- name: Copy prometheus to etc
  shell: "cp /tmp.prometheus-2.39.1.darwin-amd64/prometheus.yml /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copy consoles to etc
  shell: "cp -r /tmp/prometheus-2.39.1.darwin-amd64/consoles /etc/prometheus/"

- name: Copy console library to etc
  shell: "cp -r /tmp/prometheus-2.39.1.darwin-amd64/console_libraries /etc/prometheus/"

- name: Copy prometheus system service
  copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.sile /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service
    mode: "0755"

- name: Start and enable service
  service:
    name: prometheus
    state: started
    enabled: yes


# tasks file for prometheus_centos
